### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by yocontra** [nsfmc/atoll.js#2]
Can you publish this to npm?

**Comment by nsfmc** [comment]
sure thing, gimme a little while (or if you have a package.json handy already, i'd be happy to pull it in).

**Comment by nsfmc** [comment]
@Contra it's in npm now, the build script says it has a fatal error since it doesn't pull down the git repo when installing, but the requisite atoll = require("atoll") works, so go nuts.

**Comment by yocontra** [comment]
You want to set the main file of the package.json to a prebuilt version - building on install usually causes problems when going cross-platform
