### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by ldstein** [nsfmc/atoll.js#6]
Hi,

I've been working on adding [Windows compatiblity](https://github.com/mcollina/mosca/pull/77) to [Mosca](http://github.com/mcollina/mosca) which has Atoll as one of it's dependencies.

One blocker I'm facing is Atoll currently has an install script defined: `"install": "make atoll"` which doesn't run on Windows.

Since all the Makefile does is generates a minified version of Atoll.js, would it be possible to change:

``` js
  "scripts": {
    "install": "make atoll"
  },
```

to:

``` js
  "scripts": {
    "prepublish": "make atoll"
  },
```

This will include `/dist/atoll.js` in the release and remove the need for this compile step.

To quote the [NPM Script docs](https://npmjs.org/doc/misc/npm-scripts.html):

"If you have to do other things before your package is used, in a way that is not dependent on the operating system or architecture of the target system, then use a prepublish script instead. This includes tasks such as:
- Compile CoffeeScript source code into JavaScript.
- Create minified versions of JavaScript source code.
- Fetching remote resources that your package will use.

The advantage of doing these things at prepublish time instead of preinstall or install time is that they can be done once, in a single place, and thus greatly reduce complexity and variability. "

Kind Regards,

Leo

**Comment by nsfmc** [comment]
Hi Leo, as you can see, atoll is old enough so that the current prepublish vs install dogma is new to it. thanks so much for reporting and making it an easy change for me. please let me know if you have any other issues. sorry for any delays this may have caused you.

**Comment by ldstein** [comment]
Happy to confirm v0.7.4 is now playing nicely on Windows.

Many thanks for the quick turnaround!
